# config/packages/liip_imagine.yaml
liip_imagine:
    # Définissez ici le répertoire où les images transformées seront stockées en cache
    cache: default # Assurez-vous que le cache est configuré ici
    data_loader: default

    twig:
        mode: lazy # Votre configuration existante

    resolvers:
        default:
            web_path: ~

    filter_sets:
        # Vos filtres existants
        thumbs:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: inset }

        big_thumbs:
            quality: 100
            filters:
                thumbnail: { size: [600, 600], mode: inset }

        boite:
            quality: 100
            filters:
                thumbnail: { size: [300, 300], mode: inset }

        # Les nouveaux filtres pour les images de QuoteRequestLine
        # Un filtre pour une miniature carrée de 120x120 pixels
        thumb_120x120:
            quality: 75
            filters:
                thumbnail:
                    size: [120, 120]
                    mode: outbound # Redimensionne et recadre pour remplir la taille, coupe les bords

        # Un filtre pour une image de taille moyenne, largeur max 800px, hauteur auto
        medium_800:
            quality: 85
            filters:
                thumbnail:
                    size: [800, ~] # ~ signifie que la hauteur est calculée automatiquement pour maintenir les proportions
                    mode: inset # Redimensionne l'image pour qu'elle tienne dans la taille spécifiée, sans recadrage

        # Un filtre pour une image de grande taille, largeur max 1200px, hauteur auto
        large_1200:
            quality: 90
            filters:
                thumbnail:
                    size: [1200, ~]
                    mode: inset