vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        boites:
            uri_prefix: '%app.path.boites_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.boites_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        partners:
            uri_prefix: '%app.path.partners_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.partners_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        itemGroup:
            uri_prefix: '%app.path.itemGroup_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.itemGroup_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        item:
            uri_prefix: '%app.path.item_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.item_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
